---
# tasks file for simplesamlphp

- name: Install PHP
  apt:
    name: php
    state: latest

- name: Check if SimpleSAMLphp is already installed
  stat:
    path: /var/simplesamlphp
  register: simplesamlphp

- name: Clone SimpleSAMLphp from GitHub
  git:
    repo: "https://github.com/simplesamlphp/simplesamlphp.git"
    dest: /var/simplesamlphp
    version: v1.15.4
  when: simplesamlphp.stat.isdir == False

- name: Copy IdP certificate files to server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'rootCA.crt', dest: '/usr/local/share/ca-certificates/rootCA.crt' }
    - { src: 'idp.crt', dest: '/etc/ssl/certs/idp.crt' }
    - { src: 'idp.key', dest: '/etc/ssl/private/idp.key' }

- name: Update CA certificates
  command: /usr/sbin/update-ca-certificates

- name: Make sure PHP accepts the rootCA
  lineinfile:
    path: /etc/php/7.0/apache2/php.ini
    regexp: 'openssl\.cafile='
    line: 'openssl.cafile=/etc/ssl/ca-certificates.crt'