---

  - name: Install Apache2
    apt:
      name: apache2
      update_cache: yes
      state: present

  - name: Setup apache2 port and virtual host for webapp
    shell: ./setup.sh
    args:
      chdir: /vagrant/ansible/roles/apache_setup/files/
    become: true
    
...
