# Default playbook.
#
# Should configure a development setup to the point where a server or
# equivalent can be started with a single command.
---

- hosts: all

  become: true
  become_method: sudo
  become_user: root

  pre_tasks:
    - name: Update apt cache (if old)
      apt: update_cache=yes cache_valid_time=84600
      changed_when: false

  vars:
    hostname: dh.example.org

  roles:
    - common-server-configuration
    - apache
#    - simplesamlphp

...
