---

  - name: Install git
    apt:
      name: git
      update_cache: yes
      state: present

  - name: Install git-flow
    apt:
      name: git-flow
      update_cache: yes
      state: present

...
